export const MOTIVATIONAL_QUOTES: string[] = [
  'One more rep.',
  'Pain is temporary.',
  'Earn it today.',
  "No excuses, just results.",
  'Push past your limits.',
  'Stronger than yesterday.',
  'Finish what you started.',
  "Don't stop now.",
  'Make it burn.',
  'Comfort zones kill progress.',
  'Show up. Every time.',
  'Effort beats talent.',
  'Sweat now, shine later.',
  'Build the discipline.',
  'Your only competition is you.',
  'Leave it all here.',
  'Progress over perfection.',
  'Chase the pump.',
  'Discomfort is growth.',
  'Own this set.',
  'Rest later, work now.',
  'Beast mode activated.',
  'Grind in silence.',
  'Strong body, strong mind.',
  'Lift heavy, live free.',
  "You've got this.",
  'Break your own record.',
  'Fuel the fire.',
  'Turn pain into power.',
  'Reps build character.',
  'Small steps, big gains.',
  'Trust the process.',
  'Do it for future you.',
  "Excuses don't build muscle.",
  'Attack every rep.',
  'Feel the burn, embrace it.',
  'Consistency conquers everything.',
  'Fall down, get up.',
  'Prove yourself wrong.',
  "Today's effort, tomorrow's strength.",
  'Never skip leg day.',
  'Dig a little deeper.',
  'Fight for every inch.',
  'Redefine your limits.',
  'Failure fuels growth.',
  'Champions train, others complain.',
  'Move with purpose.',
  "Willpower over won't-power.",
  'Keep moving forward.',
  'Become unstoppable.',
];

export function randomQuote(): string {
  return MOTIVATIONAL_QUOTES[Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length)];
}
